name: Semgrep Caller Workflow

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep_caller.yml
  # schedule:
  #   - cron: '29 21 * * *'

jobs:
  call-semgrep:
    uses: r2c-david/semgrep-reuse/.github/workflows/semgrep_everywhere.yml@main
    secrets: inherit
